# Generated by Django 5.1.4 on 2025-01-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structruedDataQuery", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueryHistory",
        ),
        migrations.DeleteModel(
            name="UploadedData",
        ),
    ]
