# Generated by Django 5.1.4 on 2025-01-24 08:50

import django.db.models.deletion
import django.utils.timezone
import ideaGen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_idea_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductIdea2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("dynamic_fields", models.JSONField(default=dict)),
                ("number_of_ideas", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedImage2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=ideaGen.models.OverwriteStorage(),
                        upload_to=ideaGen.models.generate_unique_filename,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("parameters", models.JSONField(blank=True, null=True)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retried", "Retried"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("original_parameters", models.JSONField(blank=True, null=True)),
                ("final_parameters", models.JSONField(blank=True, null=True)),
                (
                    "idea",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ideaGen.idea",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="idea",
            name="product_idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ideas",
                to="ideaGen.productidea2",
            ),
        ),
    ]
