# Generated by Django 5.1.4 on 2025-01-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productidea2",
            name="negative_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
