# Generated by Django 5.1.4 on 2025-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0004_alter_generatedimage2_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="original_idea_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
