# Generated by Django 5.1.4 on 2025-01-06 21:09

import ideaGen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideaGen", "0005_idea_original_idea_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage2",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=ideaGen.models.OverwriteStorage(),
                upload_to=ideaGen.models.generate_unique_filename,
            ),
        ),
    ]
