# Generated by Django 5.1.4 on 2025-01-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_conversationmemorybuffer_conversation_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmemorybuffer",
            name="conversation_history",
        ),
    ]
